### ISSUE TITLE
403 Forbidden Request forbidden

### ISSUE THREAD

**Issue by gerisse** [mozilla-iot/webthing-upy#17]
hi
i did in my esp32 heltec : i have the good messages :+1: 
>>> start.thing()
(...)INFO:sparkfun_esp32_thing:starting the server
INFO:server:Starting Web Server on port 80

but Firefox says : 
 _403 Forbidden Request forbidden -- authorization will not help_ 
an idea ?
Thanks

**Comment by mrstegeman** [comment]
403 is only ever returned by the server is you try to access it via the wrong hostname/IP address. It appears that you must access it via one of the following:
* localhost/127.0.0.1 (probably not possible, in your case)
* esp32-upy-xx-yy-zz (where xx, yy, zz are the last 6 digits of the MAC address)
* hostname.local (where hostname is something you passed into the WebThingServer instance)
* the IP address

**Comment by brianpeiris** [comment]
I ran into this issue as well. If I'm not mistaken, the problem is that the `validateHost` function attempts to retrieve the "host" header, when actually the header name is case sensitive and is actually "Host", with a capital "H".

https://github.com/mozilla-iot/webthing-upy/blob/33f5b0d11d02ada50022187e2614d08c39925bcb/webthing/server.py#L267

**Comment by mrstegeman** [comment]
In the MicroWebSrv source, it looks like headers are all normalized: https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/blob/c9b9dd184e698bd77ff4fa50ad8564e2258fb4e8/MicroPython_BUILD/components/micropython/esp32/modules/microWebSrv.py#L453

Is that not working as it should?

**Comment by brianpeiris** [comment]
Hmm, you're right, microWebSrv.py in the `rest-improvements` fork of MicroPython does indeed lower case its headers: 

https://github.com/dhylands/MicroPython_ESP32_psRAM_LoBo/blob/rest-improvements/MicroPython_BUILD/components/micropython/esp32/modules/microWebSrv.py#L454

In retrospect, I think I ran into this issue when I mistakenly attempted to use the official micropython firmware instead of building and running the `rest-improvements` version. So, disregard my previous comment. 

Thanks.
